In [ ]:
import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
from scipy.interpolate import RegularGridInterpolator

# Define known data points
x = np.array([0, 1, 2, 3])
y = np.array([0, 1, 2, 3])
z = np.array([[1, 4, 3, 6],
              [3, 2, 4, 1],
              [2, 3, 1, 5],
              [4, 1, 6, 2]])

# Create an interpolation function using bilinear interpolation
f = RegularGridInterpolator((x, y), z, method='linear', bounds_error=False, fill_value=None)

# Evaluate the interpolation function at new points
x_new = np.array([1.5, 2.5])
y_new = np.array([0.5, 1.5])
z_new = f(np.column_stack((x_new, y_new)))

print(f"The interpolated values of z at ({x_new}, {y_new}) are {z_new}")


The interpolated values of z at ([1.5 2.5], [0.5 1.5]) are [2.5  2.75]


In [ ]:
# Evaluate the interpolation function at new points
x_new = np.array([1.5])
y_new = np.array([0.5])
z_new = f(np.column_stack((x_new, y_new)))

print(f"The interpolated values of z at ({x_new}, {y_new}) are {z_new}")

The interpolated values of z at ([1.5], [0.5]) are [2.5]


In [ ]:
hackathon_file_location = '/content/drive/MyDrive/hackathon.h5'
df_hackathon = h5py.File(hackathon_file_location, 'r')
bedmachine_file_location = '/content/drive/MyDrive/bed_BedMachine.h5'
df_bedmachine = h5py.File(bedmachine_file_location, 'r')



In [ ]:
bed_BedMachine =df_bedmachine.get('bed_BedMachine')
bed_BedMachine=np.array(bed_BedMachine)
bed_BedMachine

array([[192.54895, 176.59802, 164.97534, ..., 557.7349 , 558.06384,
        560.96704],
       [195.76892, 180.4939 , 166.89478, ..., 551.7234 , 551.8322 ,
        555.66876],
       [199.5365 , 183.78601, 169.0398 , ..., 542.25824, 545.25684,
        546.88165],
       ...,
       [157.92041, 158.49365, 159.04663, ..., 410.15747, 409.583  ,
        410.25977],
       [155.57715, 156.13306, 156.66846, ..., 405.36963, 405.5818 ,
        405.29053],
       [152.85498, 153.39233, 153.3999 , ..., 400.5869 , 400.76782,
        400.7566 ]], dtype=float32)

In [ ]:
#bed_BedMachine_array=np.array(bed_BedMachine)


In [ ]:
#bed_BedMachine=np.array(bed_BedMachine)
#bed_BedMachine_flatten=bed_BedMachine.flatten()

In [ ]:
#bed_BedMachine_flatten.shape

In [ ]:
track_bed_training =df_hackathon.get('track_bed_training')
track_bed_training = pd.DataFrame(track_bed_training)
track_bed_training

0             1             2             3             4       \
0 -2.060374e+05 -2.059812e+05 -2.059531e+05 -2.058971e+05 -2.058413e+05   
1 -1.827384e+06 -1.827519e+06 -1.827586e+06 -1.827721e+06 -1.827856e+06   
2  5.382352e+02  5.504916e+02  5.638006e+02  5.605308e+02  5.457083e+02   

         5             6             7             8             9       ...  \
0 -2.057857e+05 -2.057302e+05 -2.056886e+05 -2.056470e+05 -2.055917e+05  ...   
1 -1.827990e+06 -1.828125e+06 -1.828227e+06 -1.828328e+06 -1.828463e+06  ...   
2  5.311980e+02  5.142937e+02  5.012729e+02  4.923016e+02  4.892823e+02  ...   

         396724        396725        396726        396727        396728  \
0 -2.780478e+05 -2.780505e+05 -2.780533e+05 -2.780562e+05 -2.780588e+05   
1 -1.720149e+06 -1.720127e+06 -1.720106e+06 -1.720086e+06 -1.720064e+06   
2  2.631079e+02  2.560241e+02  2.559489e+02  2.548794e+02  2.478405e+02   

         396729        396730        396731        396732        396733  
0 -2.780617e+05 -2.780645e+05 -2.780671e+05 -2.780697e+05 -2.780723e+05  
1 -1.720044e+06 -1.720023e+06 -1.720001e+06 -1.719981e+06 -1.719959e+06  
2  2.408906e+02  2.409561e+02  2.339927e+02  2.270397e+02  2.270641e+02  

[3 rows x 396734 columns]

In [ ]:
track_bed_testing =df_hackathon.get('track_bed_testing')
track_bed_testing = pd.DataFrame(track_bed_testing)
track_bed_testing

0             1             2             3             4       \
0 -2.200383e+05 -2.200384e+05 -2.200386e+05 -2.200389e+05 -2.200393e+05   
1 -1.697568e+06 -1.697642e+06 -1.697789e+06 -1.697936e+06 -1.698083e+06   

         5             6             7             8             9       ...  \
0 -2.200397e+05 -2.200399e+05 -2.200402e+05 -2.200406e+05 -2.200411e+05  ...   
1 -1.698231e+06 -1.698304e+06 -1.698451e+06 -1.698599e+06 -1.698746e+06  ...   

         235962        235963        235964        235965        235966  \
0 -2.418088e+05 -2.418207e+05 -2.418323e+05 -2.418439e+05 -2.418558e+05   
1 -1.871773e+06 -1.871755e+06 -1.871737e+06 -1.871719e+06 -1.871700e+06   

         235967        235968        235969        235970        235971  
0 -2.418674e+05 -2.418793e+05 -2.418909e+05 -2.420553e+05 -2.420668e+05  
1 -1.871682e+06 -1.871664e+06 -1.871645e+06 -1.871391e+06 -1.871373e+06  

[2 rows x 235972 columns]

In [ ]:
track_x = track_bed_training.iloc[0][:]
track_x

0        -206037.406250
1        -205981.171875
2        -205953.109375
3        -205897.078125
4        -205841.328125
              ...      
396729   -278061.656250
396730   -278064.468750
396731   -278067.125000
396732   -278069.656250
396733   -278072.343750
Name: 0, Length: 396734, dtype: float64

In [ ]:
track_y = track_bed_training.iloc[1][:]
track_y

0        -1827384.000
1        -1827518.625
2        -1827586.125
3        -1827720.750
4        -1827855.625
             ...     
396729   -1720043.625
396730   -1720023.125
396731   -1720001.375
396732   -1719980.875
396733   -1719959.250
Name: 1, Length: 396734, dtype: float64

In [ ]:
bed_groundtruth = track_bed_training.iloc[2][:]
bed_groundtruth

0         538.235168
1         550.491638
2         563.800598
3         560.530823
4         545.708252
             ...    
396729    240.890564
396730    240.956131
396731    233.992737
396732    227.039673
396733    227.064072
Name: 2, Length: 396734, dtype: float64

In [ ]:
#bed_BedMachine =df_02.get('bed_BedMachine')
#bed_BedMachine = pd.DataFrame(bed_BedMachine)
#data_bedmachine = np.array([bed_BedMachine]).T
#ata_bedmachine

In [ ]:
surf_x =df_bedmachine.get('surf_x')
surf_x = pd.DataFrame(surf_x)
surf_x

In [ ]:
x = surf_x.iloc[:][0]
x

In [ ]:
surf_y =df_bedmachine.get('surf_y')
surf_y = pd.DataFrame(surf_y)
surf_y

In [ ]:
y = surf_y.iloc[0][:]
y

0      -1697525.0
1      -1697675.0
2      -1697825.0
3      -1697975.0
4      -1698125.0
          ...    
1196   -1876925.0
1197   -1877075.0
1198   -1877225.0
1199   -1877375.0
1200   -1877525.0
Name: 0, Length: 1201, dtype: float32

In [ ]:
# interpolation of training data using surf_x(0) and surf_y(1)
from scipy.interpolate import RegularGridInterpolator
import numpy as np
import matplotlib.pyplot as plt
x = surf_x.iloc[:][0]
y = surf_y.iloc[0][:]
interp = RegularGridInterpolator((x, y),bed_BedMachine, bounds_error=False, fill_value=None)
interpolated_bedmachine = interp((track_bed_training.iloc[0][:], track_bed_training.iloc[1][:]))
interpolated_bedmachine

array([484.29138229, 484.01289827, 483.91233229, ..., 233.54048655,
       232.77649187, 231.96939687])

In [ ]:
type(interpolated_bedmachine)

numpy.ndarray

In [ ]:
# converting dataframe to numpy array
track_bed_training_arr = track_bed_training.to_numpy()
track_bed_training_arr

array([[-2.06037406e+05, -2.05981172e+05, -2.05953109e+05, ...,
        -2.78067125e+05, -2.78069656e+05, -2.78072344e+05],
       [-1.82738400e+06, -1.82751862e+06, -1.82758612e+06, ...,
        -1.72000138e+06, -1.71998088e+06, -1.71995925e+06],
       [ 5.38235168e+02,  5.50491638e+02,  5.63800598e+02, ...,
         2.33992737e+02,  2.27039673e+02,  2.27064072e+02]])

In [ ]:
# numpy array to store the training data with interpolated variables
track_bed_training_T_interpotale = np.zeros((4,track_bed_training_arr.shape[1]))
track_bed_training_T_interpotale[0:3,:] = track_bed_training_arr[0:3,:]
#track_bed_training_T_interpotale[0,:], track_bed_training.iloc[0], track_bed_training_arr[0,:]
track_bed_training_T_interpotale

array([[-2.06037406e+05, -2.05981172e+05, -2.05953109e+05, ...,
        -2.78067125e+05, -2.78069656e+05, -2.78072344e+05],
       [-1.82738400e+06, -1.82751862e+06, -1.82758612e+06, ...,
        -1.72000138e+06, -1.71998088e+06, -1.71995925e+06],
       [ 5.38235168e+02,  5.50491638e+02,  5.63800598e+02, ...,
         2.33992737e+02,  2.27039673e+02,  2.27064072e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [ ]:
track_bed_training_T_interpotale

array([[-2.06037406e+05, -2.05981172e+05, -2.05953109e+05, ...,
        -2.78067125e+05, -2.78069656e+05, -2.78072344e+05],
       [-1.82738400e+06, -1.82751862e+06, -1.82758612e+06, ...,
        -1.72000138e+06, -1.71998088e+06, -1.71995925e+06],
       [ 5.38235168e+02,  5.50491638e+02,  5.63800598e+02, ...,
         2.33992737e+02,  2.27039673e+02,  2.27064072e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [ ]:
#track_bed_training_T_interpotale_df = pd.DataFrame(data = interpolated_bedmachine)
track_bed_training_T_interpotale[3,:] = interpolated_bedmachine
track_bed_training_T_interpotale_df = pd.DataFrame(data = track_bed_training_T_interpotale.T, columns = ['track_x', 'track_y', 'target', 'bed_machine'])
track_bed_training_T_interpotale_df

track_x      track_y      target  bed_machine
0      -206037.406250 -1827384.000  538.235168   484.291382
1      -205981.171875 -1827518.625  550.491638   484.012898
2      -205953.109375 -1827586.125  563.800598   483.912332
3      -205897.078125 -1827720.750  560.530823   483.171844
4      -205841.328125 -1827855.625  545.708252   481.979672
...               ...          ...         ...          ...
396729 -278061.656250 -1720043.625  240.890564   235.117712
396730 -278064.468750 -1720023.125  240.956131   234.349890
396731 -278067.125000 -1720001.375  233.992737   233.540487
396732 -278069.656250 -1719980.875  227.039673   232.776492
396733 -278072.343750 -1719959.250  227.064072   231.969397

[396734 rows x 4 columns]

In [ ]:
## Writing interpolated data in CSV format
track_bed_training_T_interpotale=track_bed_training_T_interpotale_df.to_csv('track_bed_training_interpotale.csv', index=False)

In [ ]:
hackathon_solution_file_location = '/content/hackathon_solution.h5'
df_hackathon_solution = h5py.File(hackathon_solution_file_location, 'r')

#bed_BedMachine_test =df_hackathon_solution.get('track_bed_testing')
#bed_BedMachine_test=np.array(bed_BedMachine_test)
#bed_BedMachine_test

In [ ]:
track_bed_testing =df_hackathon_solution.get('track_bed_testing')
track_bed_testing = pd.DataFrame(track_bed_testing)
track_bed_testing

0             1             2             3             4       \
0 -2.200383e+05 -2.200384e+05 -2.200386e+05 -2.200389e+05 -2.200393e+05   
1 -1.697568e+06 -1.697642e+06 -1.697789e+06 -1.697936e+06 -1.698083e+06   
2  3.559614e+02  3.635703e+02  3.782978e+02  3.904904e+02  3.916742e+02   

         5             6             7             8             9       ...  \
0 -2.200397e+05 -2.200399e+05 -2.200402e+05 -2.200406e+05 -2.200411e+05  ...   
1 -1.698231e+06 -1.698304e+06 -1.698452e+06 -1.698599e+06 -1.698746e+06  ...   
2  3.949558e+02  3.982959e+02  4.017264e+02  4.039883e+02  4.061511e+02  ...   

         235962        235963        235964        235965        235966  \
0 -2.418088e+05 -2.418207e+05 -2.418323e+05 -2.418439e+05 -2.418558e+05   
1 -1.871773e+06 -1.871755e+06 -1.871737e+06 -1.871719e+06 -1.871700e+06   
2  5.990311e+02  5.850154e+02  5.850388e+02  5.780992e+02  5.711619e+02   

         235967        235968        235969        235970        235971  
0 -2.418674e+05 -2.418793e+05 -2.418909e+05 -2.420552e+05 -2.420668e+05  
1 -1.871682e+06 -1.871664e+06 -1.871646e+06 -1.871391e+06 -1.871373e+06  
2  5.642097e+02  5.642252e+02  5.632264e+02  9.428146e+01  1.002415e+02  

[3 rows x 235972 columns]

In [ ]:
# interpolation of training data using surf_x(0) and surf_y(1)
from scipy.interpolate import RegularGridInterpolator
import numpy as np
import matplotlib.pyplot as plt
x = surf_x.iloc[:][0]
y = surf_y.iloc[0][:]
interp = RegularGridInterpolator((x, y),bed_BedMachine, bounds_error=False, fill_value=None)
interpolated_bedmachine_test = interp((track_bed_testing.iloc[0][:], track_bed_testing.iloc[1][:]))
interpolated_bedmachine_test

array([379.83523267, 381.43893202, 384.35213714, ..., 161.29288649,
       109.32102773, 105.70654046])

In [ ]:
interpolated_bedmachine_test.shape

(235972,)

In [ ]:
type(interpolated_bedmachine_test)

numpy.ndarray

In [ ]:
# converting dataframe to numpy array
track_bed_testing_arr = track_bed_testing.to_numpy()
track_bed_testing_arr

array([[-2.20038297e+05, -2.20038406e+05, -2.20038641e+05, ...,
        -2.41890906e+05, -2.42055250e+05, -2.42066844e+05],
       [-1.69756800e+06, -1.69764162e+06, -1.69778875e+06, ...,
        -1.87164550e+06, -1.87139088e+06, -1.87137262e+06],
       [ 3.55961426e+02,  3.63570251e+02,  3.78297791e+02, ...,
         5.63226440e+02,  9.42814560e+01,  1.00241531e+02]])

In [ ]:
# numpy array to store the training data with interpolated variables
track_bed_testing_T_interpotale = np.zeros((4,track_bed_testing_arr.shape[1]))
track_bed_testing_T_interpotale[0:3,:] = track_bed_testing_arr[0:3,:]
#track_bed_training_T_interpotale[0,:], track_bed_training.iloc[0], track_bed_training_arr[0,:]
track_bed_testing_T_interpotale

array([[-2.20038297e+05, -2.20038406e+05, -2.20038641e+05, ...,
        -2.41890906e+05, -2.42055250e+05, -2.42066844e+05],
       [-1.69756800e+06, -1.69764162e+06, -1.69778875e+06, ...,
        -1.87164550e+06, -1.87139088e+06, -1.87137262e+06],
       [ 3.55961426e+02,  3.63570251e+02,  3.78297791e+02, ...,
         5.63226440e+02,  9.42814560e+01,  1.00241531e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [ ]:
#track_bed_training_T_interpotale_df = pd.DataFrame(data = interpolated_bedmachine)
track_bed_testing_T_interpotale[3,:] = interpolated_bedmachine_test
track_bed_testing_T_interpotale_df = pd.DataFrame(data = track_bed_testing_T_interpotale.T, columns = ['track_x', 'track_y', 'target', 'bed_machine'])
track_bed_testing_T_interpotale_df

track_x      track_y      target  bed_machine
0      -220038.296875 -1697568.000  355.961426   379.835233
1      -220038.406250 -1697641.625  363.570251   381.438932
2      -220038.640625 -1697788.750  378.297791   384.352137
3      -220038.937500 -1697936.125  390.490387   386.982756
4      -220039.328125 -1698083.250  391.674225   389.207615
...               ...          ...         ...          ...
235967 -241867.390625 -1871682.000  564.209717   168.790475
235968 -241879.312500 -1871663.750  564.225159   165.027493
235969 -241890.906250 -1871645.500  563.226440   161.292886
235970 -242055.250000 -1871390.875   94.281456   109.321028
235971 -242066.843750 -1871372.625  100.241531   105.706540

[235972 rows x 4 columns]

In [ ]:
## Writing interpolated data in CSV format
track_bed_testing_T_interpotale=track_bed_testing_T_interpotale_df.to_csv('track_bed_testing_interpotale.csv', index=False)

In [ ]:
train='/content/track_bed_training_interpotale.csv'
test='/content/track_bed_testing_interpotale.csv'

In [ ]:
train = pd.read_csv(train)
test = pd.read_csv(test)

In [ ]:
data_full_known = pd.concat([train, test])

In [ ]:
data_full_known=data_full_known.to_csv('physics_train_test_combined.csv',index=False)